# Generated by Django 4.2.7 on 2025-09-10 20:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50, verbose_name='Número do Lote')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('quantidade_atual', models.PositiveIntegerField(default=0, verbose_name='Quantidade Atual')),
                ('quantidade_inicial', models.PositiveIntegerField(verbose_name='Quantidade Inicial')),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Unitário')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.medicamento', verbose_name='Medicamento')),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.ubs', verbose_name='UBS')),
            ],
            options={
                'verbose_name': 'Lote de Medicamento',
                'verbose_name_plural': 'Lotes de Medicamentos',
                'ordering': ['data_validade', 'numero_lote'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferência')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('destino_detalhado', models.CharField(blank=True, choices=[('paciente', 'Paciente'), ('ubs', 'UBS'), ('descarte', 'Descarte'), ('transferencia', 'Transferência')], max_length=20, null=True, verbose_name='Destino Detalhado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.lotemedicamento', verbose_name='Lote')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.medicamento', verbose_name='Medicamento')),
                ('ubs_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_destino', to='ubs.ubs', verbose_name='UBS de Destino')),
                ('ubs_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_origem', to='ubs.ubs', verbose_name='UBS de Origem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueMinimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_minima', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade Mínima')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.medicamento', verbose_name='Medicamento')),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubs.ubs', verbose_name='UBS')),
            ],
            options={
                'verbose_name': 'Estoque Mínimo',
                'verbose_name_plural': 'Estoques Mínimos',
                'unique_together': {('medicamento', 'ubs')},
            },
        ),
    ]
