# Generated by Django 4.2.7 on 2025-09-10 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Medicamento',
                'verbose_name_plural': 'Categorias de Medicamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Medicamento')),
                ('principio_ativo', models.CharField(max_length=200, verbose_name='Princípio Ativo')),
                ('dosagem', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dosagem')),
                ('unidade_medida', models.CharField(choices=[('mg', 'Miligrama (mg)'), ('g', 'Grama (g)'), ('ml', 'Mililitro (ml)'), ('l', 'Litro (l)'), ('un', 'Unidade'), ('cx', 'Caixa'), ('amp', 'Ampola'), ('frasco', 'Frasco')], max_length=10, verbose_name='Unidade de Medida')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicamentos.categoriamedicamento', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nome'],
                'unique_together': {('nome', 'dosagem', 'unidade_medida')},
            },
        ),
    ]
